# Simple E2E Test 3 - Namespace ConfigMap by Label
output_dir: "./logs"
log_level: "info"
auto_shutdown_sec: 120

namespaces:
  - name_pattern: "faro-*"
    resources:
      "v1/configmaps":
        name_pattern: "test-config-1"
        label_selector: "app=faro-test"