# Simple E2E Test 6 - Combined: Namespace + ConfigMap monitoring
output_dir: "./logs"
log_level: "info"
auto_shutdown_sec: 120

# Monitor cluster-scoped namespace resource
resources:
  - gvr: "v1/namespaces"
    scope: "Cluster"
    name_pattern: "faro-test-1"

# Monitor namespace-scoped configmaps
namespaces:
  - name_pattern: "faro-test-1"
    resources:
      "v1/configmaps":
        name_pattern: "test-config-1"