# Simple E2E Test 5 - Namespace monitoring only
output_dir: "./logs"
log_level: "info"
auto_shutdown_sec: 120

# Monitor cluster-scoped namespace resource
resources:
  - gvr: "v1/namespaces"
    scope: "Cluster"
    name_pattern: "faro-*"
