# Simple E2E Test 1 - Namespace-centric ConfigMap by name
output_dir: "./logs"
log_level: "info"
auto_shutdown_sec: 120

namespaces:
  - name_pattern: "faro-test-1"
    resources:
      "v1/configmaps":
        name_pattern: "test-config-1"