# Simple E2E Test 4 - Resource ConfigMap by Label
output_dir: "./logs"
log_level: "info"
auto_shutdown_sec: 120

resources:
  - gvr: "v1/configmaps"
    scope: "Namespaced"
    namespace_patterns:
      - "faro-test-1"
    name_pattern: "test-config-1"
    label_pattern: "app=^faro-test$"